/** Auto-generado desde public/images/teaser/nuevas — no editar a mano */
import type { StockImage } from "./stockImages";

export const TEASER_NUEVAS_BOSQUE: StockImage[] = [
  { id: "nueva-alec-krum-ng7r-1nlig0-unsplash", label: "Alec Krum NG7r_1NlIg0", url: "/images/teaser/nuevas/alec-krum-NG7r_1NlIg0-unsplash.jpg" },
  { id: "nueva-amir-maleky-jygoittxgng-unsplash", label: "Amir Maleky JYgoITTxgNg", url: "/images/teaser/nuevas/amir-maleky-JYgoITTxgNg-unsplash.jpg" },
  { id: "nueva-annie-spratt-77faqk66ixc-unsplash", label: "Annie Spratt 77Faqk66Ixc", url: "/images/teaser/nuevas/annie-spratt-77Faqk66Ixc-unsplash.jpg" },
  { id: "nueva-annie-spratt-ng7vum7sbm8-unsplash", label: "Annie Spratt NG7vuM7SBm8", url: "/images/teaser/nuevas/annie-spratt-nG7vuM7SBm8-unsplash.jpg" },
  { id: "nueva-ardian-lumi-72uqwsqaiwg-unsplash", label: "Ardian Lumi 72uqWSqAiWg", url: "/images/teaser/nuevas/ardian-lumi-72uqWSqAiWg-unsplash.jpg" },
  { id: "nueva-charlesdeluvio-j1xy5vqrtsm-unsplash", label: "Charlesdeluvio J1xy5vQRTSM", url: "/images/teaser/nuevas/charlesdeluvio-j1xy5vQRTSM-unsplash.jpg" },
  { id: "nueva-darya-jum-vswzcbv4ma8-unsplash", label: "Darya Jum VSWzcbV4Ma8", url: "/images/teaser/nuevas/darya-jum-VSWzcbV4Ma8-unsplash.jpg" },
  { id: "nueva-dmytro-koplyk-rfpa05ckcu4-unsplash", label: "Dmytro Koplyk RfPA05CKCu4", url: "/images/teaser/nuevas/dmytro-koplyk-rfPA05CKCu4-unsplash.jpg" },
  { id: "nueva-fusco-studio-6my-ab-arn4-unsplash", label: "Fusco Studio 6My Ab_Arn4", url: "/images/teaser/nuevas/fusco-studio-6My-ab_Arn4-unsplash.jpg" },
  { id: "nueva-ian-dooley-vdlqugkr3s4-unsplash", label: "Ian Dooley VDLQUgkr3S4", url: "/images/teaser/nuevas/ian-dooley-VDLQUgkr3S4-unsplash.jpg" },
  { id: "nueva-james-adams-bshgwmv9wge-unsplash", label: "James Adams BSHgWMV9WgE", url: "/images/teaser/nuevas/james-adams-BSHgWMV9WgE-unsplash.jpg" },
  { id: "nueva-juan-saav-ifbxpq6opqe-unsplash", label: "Juan Saav IFBXPq6opqE", url: "/images/teaser/nuevas/juan-saav-iFBXPq6opqE-unsplash.jpg" },
  { id: "nueva-klara-kulikova-vfkc3fdfehs-unsplash", label: "Klara Kulikova VfkC3fDfeHs", url: "/images/teaser/nuevas/klara-kulikova-VfkC3fDfeHs-unsplash.jpg" },
  { id: "nueva-lifetime-leather-x875kk9-rnu-unsplash", label: "Lifetime Leather X875kk9 RnU", url: "/images/teaser/nuevas/lifetime-leather-X875kk9-rnU-unsplash.jpg" },
  { id: "nueva-marcel-strauss-zdxv79eghfy-unsplash", label: "Marcel Strauss ZdXV79EGHFY", url: "/images/teaser/nuevas/marcel-strauss-ZdXV79EGHFY-unsplash.jpg" },
  { id: "nueva-mert-kahveci-ygot2ok6jrq-unsplash", label: "Mert Kahveci YGoT2ok6jRQ", url: "/images/teaser/nuevas/mert-kahveci-YGoT2ok6jRQ-unsplash.jpg" },
  { id: "nueva-nahid-hatami-n6i9fty-n7q-unsplash", label: "Nahid Hatami N6I9fTy_n7Q", url: "/images/teaser/nuevas/nahid-hatami-N6I9fTy_n7Q-unsplash.jpg" },
  { id: "nueva-o-kunh-o0hlqih8qhu-unsplash", label: "O Kunh O0hLQIh8QhU", url: "/images/teaser/nuevas/o-kunh-o0hLQIh8QhU-unsplash.jpg" },
  { id: "nueva-pavel-okrema-fymurzs34ja-unsplash", label: "Pavel Okrema FYMurZs34jA", url: "/images/teaser/nuevas/pavel-okrema-FYMurZs34jA-unsplash.jpg" },
  { id: "nueva-rick-lobs-ruomnz9im3i-unsplash", label: "Rick Lobs RuOmNZ9iM3I", url: "/images/teaser/nuevas/rick-lobs-RuOmNZ9iM3I-unsplash.jpg" },
  { id: "nueva-seungwon-park-ntbjvxhffmo-unsplash", label: "Seungwon Park NtbjVxhffmo", url: "/images/teaser/nuevas/seungwon-park-ntbjVxhffmo-unsplash.jpg" },
  { id: "nueva-terren-hurst-mf1mb9mncfg-unsplash", label: "Terren Hurst Mf1Mb9mNCFg", url: "/images/teaser/nuevas/terren-hurst-mf1Mb9mNCFg-unsplash.jpg" },
  { id: "nueva-tony-litvyak-snb2-gvpey-unsplash", label: "Tony Litvyak  Snb2_GVpEY", url: "/images/teaser/nuevas/tony-litvyak--snb2_GVpEY-unsplash.jpg" },
  { id: "nueva-zoshua-colah-4ydpojffwaa-unsplash", label: "Zoshua Colah 4YdPoJFFWAA", url: "/images/teaser/nuevas/zoshua-colah-4YdPoJFFWAA-unsplash.jpg" },
];

export const TEASER_NUEVAS_FUEGO: StockImage[] = [
  { id: "nueva-ali-kazal-l79oysj5ftq-unsplash", label: "Ali Kazal L79oYsj5FTQ", url: "/images/teaser/nuevas/ali-kazal-L79oYsj5FTQ-unsplash.jpg" },
  { id: "nueva-amir-maleky-s0qdp5g-oj4-unsplash", label: "Amir Maleky S0Qdp5g_OJ4", url: "/images/teaser/nuevas/amir-maleky-s0Qdp5g_OJ4-unsplash.jpg" },
  { id: "nueva-annie-spratt-adhy6hs4sis-unsplash", label: "Annie Spratt ADhy6hS4sIs", url: "/images/teaser/nuevas/annie-spratt-ADhy6hS4sIs-unsplash.jpg" },
  { id: "nueva-annie-spratt-swg5qzkntx0-unsplash", label: "Annie Spratt Swg5qZkNtX0", url: "/images/teaser/nuevas/annie-spratt-swg5qZkNtX0-unsplash.jpg" },
  { id: "nueva-cesar-cabrera-azqlozh2dzk-unsplash", label: "Cesar Cabrera AZqloZH2dzk", url: "/images/teaser/nuevas/cesar-cabrera-aZqloZH2dzk-unsplash.jpg" },
  { id: "nueva-christelle-hayek-idd7hb87cda-unsplash", label: "Christelle Hayek IdD7HB87CdA", url: "/images/teaser/nuevas/christelle-hayek-IdD7HB87CdA-unsplash.jpg" },
  { id: "nueva-davidson-l-u-n-a-xwfwjrhjs54-unsplash", label: "Davidson L U N A XWFwjRHjS54", url: "/images/teaser/nuevas/davidson-l-u-n-a-XWFwjRHjS54-unsplash.jpg" },
  { id: "nueva-don-starkey-bkyk-qsknpk-unsplash", label: "Don Starkey BKYK QSKnpk", url: "/images/teaser/nuevas/don-starkey-BKYK-qSKnpk-unsplash.jpg" },
  { id: "nueva-gabriel-tovar-sennt-uj4xc-unsplash", label: "Gabriel Tovar SENNT UJ4Xc", url: "/images/teaser/nuevas/gabriel-tovar-sENNT-UJ4Xc-unsplash.jpg" },
  { id: "nueva-igor-rand-vyffspfdswe-unsplash", label: "Igor Rand VYFfSPfdsWE", url: "/images/teaser/nuevas/igor-rand-vYFfSPfdsWE-unsplash.jpg" },
  { id: "nueva-jesse-barker-4na9-syvpcs-unsplash", label: "Jesse Barker 4na9_syVpcs", url: "/images/teaser/nuevas/jesse-barker-4na9_syVpcs-unsplash.jpg" },
  { id: "nueva-julian-hochgesang-nnv5gb8z6oi-unsplash", label: "Julian Hochgesang Nnv5Gb8z6OI", url: "/images/teaser/nuevas/julian-hochgesang-Nnv5Gb8z6OI-unsplash.jpg" },
  { id: "nueva-la-compagnie-robinson-kgqlg-k4vwa-unsplash", label: "La Compagnie Robinson KGQlg K4VWA", url: "/images/teaser/nuevas/la-compagnie-robinson-KGQlg-K4VWA-unsplash.jpg" },
  { id: "nueva-logan-weaver-lgnwvr-ywndbocn0py-unsplash", label: "Logan Weaver Lgnwvr YWndBOcN0pY", url: "/images/teaser/nuevas/logan-weaver-lgnwvr-YWndBOcN0pY-unsplash.jpg" },
  { id: "nueva-margo-evardson-sfdlrgem8h8-unsplash", label: "Margo Evardson SfDLrGeM8H8", url: "/images/teaser/nuevas/margo-evardson-sfDLrGeM8H8-unsplash.jpg" },
  { id: "nueva-mikita-karasiou-maf3xccxs8-unsplash", label: "Mikita Karasiou _MAf3XCCXS8", url: "/images/teaser/nuevas/mikita-karasiou-_MAf3XCCXS8-unsplash.jpg" },
  { id: "nueva-naraa-in-ub-0zlfqvn9pjm-unsplash", label: "Naraa In Ub 0zLfqVN9pjM", url: "/images/teaser/nuevas/naraa-in-ub-0zLfqVN9pjM-unsplash.jpg" },
  { id: "nueva-pablo-hernandez-yxyycw8ioxa-unsplash", label: "Pablo Hernandez YXyYCw8ioXA", url: "/images/teaser/nuevas/pablo-hernandez-YXyYCw8ioXA-unsplash.jpg" },
  { id: "nueva-polina-fdapo0qixgq-unsplash", label: "Polina FDApO0QiXGQ", url: "/images/teaser/nuevas/polina-FDApO0QiXGQ-unsplash.jpg" },
  { id: "nueva-riven-moss-vgzmgtee5iu-unsplash", label: "Riven Moss VGzMGTEe5iU", url: "/images/teaser/nuevas/riven-moss-VGzMGTEe5iU-unsplash.jpg" },
  { id: "nueva-sonu-agvan-icxw9r1srte-unsplash", label: "Sonu Agvan Icxw9r1SrtE", url: "/images/teaser/nuevas/sonu-agvan-icxw9r1SrtE-unsplash.jpg" },
  { id: "nueva-tiago-ferreira-inocuqar-js-unsplash", label: "Tiago Ferreira INOcuqaR Js", url: "/images/teaser/nuevas/tiago-ferreira-iNOcuqaR-js-unsplash.jpg" },
  { id: "nueva-vidar-nordli-mathisen-f4oms-slujc-unsplash", label: "Vidar Nordli Mathisen F4OmS_SluJc", url: "/images/teaser/nuevas/vidar-nordli-mathisen-f4OmS_SluJc-unsplash.jpg" },
  { id: "nueva-zoshua-colah-cuka1suto5q-unsplash", label: "Zoshua Colah CUka1SutO5Q", url: "/images/teaser/nuevas/zoshua-colah-CUka1SutO5Q-unsplash.jpg" },
];

export const TEASER_NUEVAS_RITUAL: StockImage[] = [
  { id: "nueva-alina-bordunova-dmdnbwer9kk-unsplash", label: "Alina Bordunova DMDnBwER9kk", url: "/images/teaser/nuevas/alina-bordunova-DMDnBwER9kk-unsplash.jpg" },
  { id: "nueva-andrey-metelev-st5klh5ylqk-unsplash", label: "Andrey Metelev ST5Klh5YlQk", url: "/images/teaser/nuevas/andrey-metelev-sT5Klh5YlQk-unsplash.jpg" },
  { id: "nueva-annie-spratt-eop0hx9byby-unsplash", label: "Annie Spratt EoP0hx9bybY", url: "/images/teaser/nuevas/annie-spratt-EoP0hx9bybY-unsplash.jpg" },
  { id: "nueva-annie-spratt-wsjyjxtgjtc-unsplash", label: "Annie Spratt WSJyJxTGJTc", url: "/images/teaser/nuevas/annie-spratt-wSJyJxTGJTc-unsplash.jpg" },
  { id: "nueva-charlesdeluvio-qb7y8vnn-zi-unsplash", label: "Charlesdeluvio QB7y8Vnn ZI", url: "/images/teaser/nuevas/charlesdeluvio-QB7y8Vnn-ZI-unsplash.jpg" },
  { id: "nueva-cristiano-valadar-pxdhdla1b50-unsplash", label: "Cristiano Valadar PxdhDlA1B50", url: "/images/teaser/nuevas/cristiano-valadar-pxdhDlA1B50-unsplash.jpg" },
  { id: "nueva-diane-pilkington-ywjav-x-msw-unsplash", label: "Diane Pilkington YWjAV_X Msw", url: "/images/teaser/nuevas/diane-pilkington-yWjAV_X-msw-unsplash.jpg" },
  { id: "nueva-ed-stone-78u6v0mbdgw-unsplash", label: "Ed Stone 78U6V0mBdgw", url: "/images/teaser/nuevas/ed-stone-78U6V0mBdgw-unsplash.jpg" },
  { id: "nueva-gryffyn-m-pl5b-k-xk8y-unsplash", label: "Gryffyn M Pl5B K_Xk8Y", url: "/images/teaser/nuevas/gryffyn-m-pl5B-k_Xk8Y-unsplash.jpg" },
  { id: "nueva-j-lopez-dw2202yzkr4-unsplash", label: "J Lopez DW2202YZkr4", url: "/images/teaser/nuevas/j-lopez-DW2202YZkr4-unsplash.jpg" },
  { id: "nueva-joaquin-toro-td-nflhydqc-unsplash", label: "Joaquin Toro Td_NflhYdQc", url: "/images/teaser/nuevas/joaquin-toro-td_NflhYdQc-unsplash.jpg" },
  { id: "nueva-kevin-turcios-ni2zjjat9wi-unsplash", label: "Kevin Turcios NI2ZjJAt9wI", url: "/images/teaser/nuevas/kevin-turcios-nI2ZjJAt9wI-unsplash.jpg" },
  { id: "nueva-laura-louise-grimsley-wp3wpf7fivc-unsplash", label: "Laura Louise Grimsley Wp3WpF7fivc", url: "/images/teaser/nuevas/laura-louise-grimsley-Wp3WpF7fivc-unsplash.jpg" },
  { id: "nueva-maksym-tymchyk-hjk5hgtehia-unsplash", label: "Maksym Tymchyk Hjk5hgTEHIA", url: "/images/teaser/nuevas/maksym-tymchyk-Hjk5hgTEHIA-unsplash.jpg" },
  { id: "nueva-max-bender-qm9-mgycw4a-unsplash", label: "Max Bender Qm9_Mgycw4A", url: "/images/teaser/nuevas/max-bender-Qm9_Mgycw4A-unsplash.jpg" },
  { id: "nueva-moreno-matkovic-a1s-sewdgru-unsplash", label: "Moreno Matkovic A1S_sEWdgRU", url: "/images/teaser/nuevas/moreno-matkovic-A1S_sEWdgRU-unsplash.jpg" },
  { id: "nueva-nationaal-archief-nifnvokdv-o-unsplash", label: "Nationaal Archief Nifnvokdv_o", url: "/images/teaser/nuevas/nationaal-archief-Nifnvokdv_o-unsplash.jpg" },
  { id: "nueva-pavel-neznanov-d4jtuffffks-unsplash", label: "Pavel Neznanov D4JTUfFfFKs", url: "/images/teaser/nuevas/pavel-neznanov-d4JTUfFfFKs-unsplash.jpg" },
  { id: "nueva-ranurte-vft5fphftri-unsplash", label: "Ranurte Vft5FphFtRI", url: "/images/teaser/nuevas/ranurte-Vft5FphFtRI-unsplash.jpg" },
  { id: "nueva-ruby-khoesial-fjqvnfx-czm-unsplash", label: "Ruby Khoesial FjqvNFX CzM", url: "/images/teaser/nuevas/ruby-khoesial-FjqvNFX-czM-unsplash.jpg" },
  { id: "nueva-stephane-hurbe-uoqaz5ewwto-unsplash", label: "Stephane Hurbe UoQAz5EWwTo", url: "/images/teaser/nuevas/stephane-hurbe-uoQAz5EWwTo-unsplash.jpg" },
  { id: "nueva-tobias-kaiser-pwtwqiueemq-unsplash", label: "Tobias Kaiser PwTwQiuEeMQ", url: "/images/teaser/nuevas/tobias-kaiser-pwTwQiuEeMQ-unsplash.jpg" },
  { id: "nueva-wendy-scofield-tjfqr3jggg8-unsplash", label: "Wendy Scofield TjfQR3JgGG8", url: "/images/teaser/nuevas/wendy-scofield-TjfQR3JgGG8-unsplash.jpg" },
];
